{$ifdef Release}
    {$SetPEFlags
	IMAGE_FILE_RELOCS_STRIPPED or
	IMAGE_FILE_EXECUTABLE_IMAGE or
	IMAGE_FILE_LINE_NUMS_STRIPPED or
	IMAGE_FILE_LOCAL_SYMS_STRIPPED or
	IMAGE_FILE_AGGRESIVE_WS_TRIM or
	IMAGE_FILE_DEBUG_STRIPPED
    }
{$endif}
