unit IGXRProtocol_Intf;

{----------------------------------------------------------------------------}
{ This unit was automatically generated by the RemObjects SDK after reading  }
{ the RODL file associated with this project .                               }
{                                                                            }
{ Do not modify this unit manually, or your changes will be lost when this   }
{ unit is regenerated the next time you compile the project.                 }
{----------------------------------------------------------------------------}

{$I RemObjects.inc}

interface

uses
  {vcl:} Classes, TypInfo,
  {RemObjects:} uROXMLIntf, uROClasses, uROClient, uROTypes, uROClientIntf;

const
  { Library ID }
  LibraryUID = '{E947A5F5-F76D-4E1D-867B-7376E9B6C327}';
  TargetNamespace = '';

  { Service Interface ID's }
  IIGXmlRpcSrv_IID : TGUID = '{4085D285-12E1-4994-B780-740E984555CD}';

  { Event ID's }

type
  TSeekOrigin = Classes.TSeekOrigin; // fake declaration
  { Forward declarations }
  IIGXmlRpcSrv = interface;


  { IIGXmlRpcSrv }
  IIGXmlRpcSrv = interface
    ['{4085D285-12E1-4994-B780-740E984555CD}']
  end;

  { CoIGXmlRpcSrv }
  CoIGXmlRpcSrv = class
    class function Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IIGXmlRpcSrv;
  end;

  { TIGXmlRpcSrv_Proxy }
  TIGXmlRpcSrv_Proxy = class(TROProxy, IIGXmlRpcSrv)
  protected
    function __GetInterfaceName:string; override;

  end;

implementation

uses
  {vcl:} SysUtils,
  {RemObjects:} uROEventRepository, uROSerializer, uRORes;

{ CoIGXmlRpcSrv }

class function CoIGXmlRpcSrv.Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IIGXmlRpcSrv;
begin
  result := TIGXmlRpcSrv_Proxy.Create(aMessage, aTransportChannel);
end;

function TIGXmlRpcSrv_Proxy.__GetInterfaceName:string;
begin
  result := 'IGXmlRpcSrv';
end;

initialization
  RegisterProxyClass(IIGXmlRpcSrv_IID, TIGXmlRpcSrv_Proxy);


finalization
  UnregisterProxyClass(IIGXmlRpcSrv_IID);

end.
